version: '3.3'

networks:
  graylog:
    external: true

graylog-ambiente:
    image: graylog/graylog:5.1.3
    container_name: graylog
    hostname: graylog
    restart: always
    user: $USER
    volumes:
      - ./journal:/usr/share/graylog/data/journal
      - ./graylog.conf:/usr/share/graylog/data/config/graylog.conf
      - ./plugin:/usr/share/graylog/plugin
    environment:
      - GRAYLOG_ROOT_PASSWORD_SHA2=$GRAYLOG_ROOT_PASSWORD_SHA2
      - GRAYLOG_HTTP_BIND_ADDRESS=$GRAYLOG_HTTP_BIND_ADDRESS
      - GRAYLOG_HTTP_EXTERNAL_URI=http://graylog.cliente.uds.com.br/
      - GRAYLOG_TRANSPORT_EMAIL_WEB_INTERFACE_URL=http://ip:7555
      - MONGODB_URI=mongodb://mongodb
        #  - GRAYLOG_TRANSPORT_EMAIL_HOSTNAME=smtp.gmail.com
        #  - GRAYLOG_TRANSPORT_EMAIL_ENABLED=true
        #  - GRAYLOG_TRANSPORT_EMAIL_PORT=465
        #  - GRAYLOG_TRANSPORT_EMAIL_USE_AUTH=true
        #  - GRAYLOG_TRANSPORT_EMAIL_USE_TLS=true
        #  - GRAYLOG_TRANSPORT_EMAIL_USE_SSL=true
        #  - GRAYLOG_TRANSPORT_FROM_EMAIL=graylog@cardpay.com.br
        # - GRAYLOG_TRANSPORT_SUBJECT_PREFIX=[graylog]
    ports:
      # Graylog web interface and REST API
      #- 80:7555
      # Syslog TCP
      - 8514:8514
      # Syslog UDP
      - 8514:8514/udp
      # GELF TCP
      - 12201:12201
      # GELF UDP
      - 12201:12201/udp
    networks:
      - graylog
