version: '3.3'

networks:
  graylog:
    external: true

services:
  mongo:
    image: mongo:5
    hostname: mongo
    ports:
      - 27017:27017
    container_name: mongo
    volumes:
       - ./mongodb:/data/db
    networks:
      - graylog
    restart: always
